
services:
    postgres:
      image: postgis/postgis:12-2.5
      restart: always
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB} # default database
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - local_network
    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4_container
      restart: always
      # ports:
      #   - "8888:80"
      # labels:
      #   - "traefik.enable=true"
      #   - "traefik.http.routers.pgadmin.rule=Host(`localhost`)"
      #   - "traefik.http.routers.pgadmin.entrypoints=web"
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      volumes:
        - pgadmin:/var/lib/pgadmin
      networks:
        - local_network

    traefik:
      image: "traefik:v3.3"
      container_name: "traefik"
      command:
        - "--log.level=DEBUG"
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entryPoints.web.address=:80"
      ports:
        - "80:80"
        - "${TRAEFIK_DASHBORD_PORT}:8080"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
      networks:
        - local_network

networks:
  local_network:
    name: local_network

volumes:
    postgres_data:
    pgadmin: